development:
  adapter: sqlite3
  encoding: unicode
  database: base
  pool: 2
  username: Yaromir
  password: 123456
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['BASE'] %>
  username: <%= ENV['Yaromir'] %>
  password: <%= ENV['123456'] %>